language: node_js
node_js:
- '10'
before_install:    
  - pip install --user awscli
script:
  - npm test
  - npm run build
deploy:
 provider: script
 skip_cleanup: true
 script: npm run deploy
 on:
   branch: master
   tags: false

